import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/legal-shell";

export const metadata: Metadata = { title: "Política de privacidad | CartaYa", description: "Cómo CartaYa recopila, utiliza y protege los datos personales." };

export default function PrivacyPage() {
  return <LegalShell eyebrow="Privacidad" title="Tus datos deben tener un propósito claro." description="Esta política explica qué información procesa CartaYa, por qué la necesita y qué opciones tienen restaurantes, empleados y clientes.">
    <section><h2>1. Quién trata la información</h2><p>CartaYa opera la plataforma disponible en tucartaya.com. Para consultas o solicitudes sobre privacidad puedes escribir a <a href="mailto:privacidad@tucartaya.com">privacidad@tucartaya.com</a>.</p><p>Cuando un restaurante usa CartaYa para gestionar pedidos, ese restaurante decide qué información solicita a sus clientes. CartaYa actúa como proveedor tecnológico para procesarla siguiendo la configuración del restaurante.</p></section>
    <section><h2>2. Información que procesamos</h2><ul><li>Datos de cuenta del propietario: nombre, correo, teléfono, restaurante y credenciales administradas mediante Supabase Auth.</li><li>Datos operativos: menú, precios, mesas, pedidos, notas, estados, usuarios del equipo y solicitudes de asistencia.</li><li>Datos del cliente final: nombre opcional, mesa, pedido y notas que escriba voluntariamente.</li><li>Datos técnicos y de seguridad: dirección IP, navegador, registros de errores, intentos de acceso y suscripciones a notificaciones.</li></ul></section>
    <section><h2>3. Para qué usamos los datos</h2><ul><li>Prestar el servicio, autenticar cuentas y mostrar la información del restaurante correcto.</li><li>Enviar pedidos, avisos operativos y notificaciones solicitadas.</li><li>Prevenir fraude, automatización abusiva, accesos no autorizados y fallos técnicos.</li><li>Atender soporte, solicitudes de plan y obligaciones legales aplicables.</li><li>Mejorar estabilidad y experiencia usando información agregada o desidentificada.</li></ul></section>
    <section><h2>4. Proveedores tecnológicos</h2><p>Usamos proveedores que procesan información necesaria para operar CartaYa: Supabase para autenticación y base de datos, Vercel para alojamiento, Cloudflare R2 para imágenes y Web Push para notificaciones. Cuando Turnstile esté activo, Cloudflare procesará señales técnicas estrictamente necesarias para distinguir personas de bots.</p></section>
    <section><h2>5. Conservación</h2><p>Conservamos la cuenta y los datos operativos mientras el restaurante mantenga el servicio. Las suscripciones push se eliminan al desactivarlas, cuando dejan de ser válidas o al cerrar la cuenta. Los datos de pedidos se conservarán conforme al período operativo acordado con el restaurante y las obligaciones aplicables. Antes del lanzamiento comercial se publicará el período definitivo de retención y eliminación.</p></section>
    <section><h2>6. Derechos y solicitudes</h2><p>Puedes solicitar acceso, corrección, actualización o eliminación de tus datos. Si eres cliente de un restaurante, algunas solicitudes deben dirigirse primero al propio restaurante porque controla la relación y el pedido. Verificaremos la identidad antes de entregar o modificar información.</p></section>
    <section><h2>7. Seguridad y menores</h2><p>Aplicamos controles de acceso por restaurante, cifrado en tránsito, validación del servidor, límites de frecuencia y registros de seguridad. Ningún sistema es infalible; consulta nuestra <a href="/seguridad">página de seguridad</a> para conocer los controles y reportar incidentes.</p><p>CartaYa no está dirigida a crear cuentas de menores de edad. Los restaurantes deben evitar solicitar información innecesaria a menores.</p></section>
    <section><h2>8. Marco y cambios</h2><p>Esta política se interpreta de acuerdo con la normativa aplicable de la República Dominicana, incluyendo las reglas sobre protección de datos personales, comercio electrónico y derechos del consumidor. Publicaremos los cambios materiales antes de que entren en vigor.</p></section>
  </LegalShell>;
}
