import Link from "next/link";
import { ArrowLeft, Clock3, ImageIcon, LifeBuoy, LockKeyhole } from "lucide-react";
import { TicketReplyForm } from "@/components/support/ticket-reply-form";
import { Button } from "@/components/ui/button";
import { isR2Configured } from "@/lib/cloudflare/r2";
import { formatTicketNumber, requireRestaurantTicket, supportCategoryLabels, supportImpactLabels, supportStatusLabels } from "@/lib/support";

export default async function SupportTicketPage({ params, searchParams }: { params: Promise<{ ticketId: string }>; searchParams: Promise<{ created?: string; sent?: string; attachment?: string }> }) {
  const { ticketId } = await params;
  const notices = await searchParams;
  const context = await requireRestaurantTicket(ticketId);
  const [{ data: messages }, { data: attachments }] = await Promise.all([
    context.admin.from("support_messages").select("id, body, created_at, author_id, author:profiles(full_name, role)").eq("ticket_id", ticketId).eq("is_internal", false).order("created_at"),
    context.admin.from("support_attachments").select("id, message_id, original_name, mime_type, byte_size, created_at").eq("ticket_id", ticketId).order("created_at"),
  ]);
  const initialAttachments = (attachments ?? []).filter((attachment) => !attachment.message_id);

  return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-10"><Button asChild variant="ghost" className="mb-5 -ml-3 gap-2"><Link href="/dashboard/soporte"><ArrowLeft className="size-4" />Volver a soporte</Link></Button>
    {notices.created ? <p className="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">Ticket enviado. Soporte ya puede verlo.</p> : null}{notices.sent ? <p className="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">Respuesta enviada.</p> : null}{notices.attachment ? <p className="mb-5 rounded-xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800">El mensaje se guardó, pero la captura no pudo adjuntarse.</p> : null}
    <section className="rounded-3xl border bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-brand-green">{formatTicketNumber(context.ticket.ticket_number, context.ticket.created_at)}</p><h1 className="mt-2 text-2xl font-black tracking-tight text-brand-navy sm:text-3xl">{context.ticket.subject}</h1><p className="mt-2 text-sm text-slate-500">{supportCategoryLabels[context.ticket.category]} · {supportImpactLabels[context.ticket.impact]}</p></div><span className="self-start rounded-full bg-slate-100 px-3 py-2 text-xs font-black text-slate-700">{supportStatusLabels[context.ticket.status]}</span></div><div className="mt-6 rounded-2xl bg-slate-50 p-4 sm:p-5"><p className="whitespace-pre-wrap leading-7 text-slate-700">{context.ticket.description}</p><p className="mt-4 flex items-center gap-1 text-xs text-slate-400"><Clock3 className="size-3" />{new Date(context.ticket.created_at).toLocaleString("es-DO")}</p>{initialAttachments.length ? <div className="mt-4 flex flex-wrap gap-2">{initialAttachments.map((attachment) => <a key={attachment.id} href={`/api/support/attachments/${attachment.id}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-bold text-brand-orange"><ImageIcon className="size-4" />{attachment.original_name}</a>)}</div> : null}</div></section>

    <section className="mt-6 rounded-3xl border bg-white shadow-sm"><div className="border-b px-5 py-4 sm:px-7"><h2 className="font-black text-brand-navy">Conversación</h2></div><div className="space-y-4 p-5 sm:p-7">{messages?.length ? messages.map((message) => { const relation = message.author as unknown as { full_name: string; role: string } | { full_name: string; role: string }[] | null; const author = Array.isArray(relation) ? relation[0] : relation; const fromSupport = author?.role === "superadmin"; const messageAttachments = (attachments ?? []).filter((attachment) => attachment.message_id === message.id); return <article key={message.id} className={`max-w-[90%] rounded-2xl p-4 ${fromSupport ? "mr-auto bg-brand-navy text-white" : "ml-auto bg-orange-50 text-brand-navy"}`}><div className="flex items-center justify-between gap-4"><p className="text-xs font-black">{fromSupport ? "Soporte CartaYa" : author?.full_name ?? "Usuario"}</p><p className={`text-[10px] ${fromSupport ? "text-slate-400" : "text-slate-400"}`}>{new Date(message.created_at).toLocaleString("es-DO")}</p></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{message.body}</p>{messageAttachments.length ? <div className="mt-3 flex flex-wrap gap-2">{messageAttachments.map((attachment) => <a key={attachment.id} href={`/api/support/attachments/${attachment.id}`} target="_blank" rel="noreferrer" className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${fromSupport ? "bg-white/10 text-white" : "bg-white text-brand-orange"}`}><ImageIcon className="size-3" />{attachment.original_name}</a>)}</div> : null}</article>; }) : <p className="py-6 text-center text-sm text-slate-500">Soporte todavía no ha respondido.</p>}</div></section>

    <section className="mt-6 rounded-3xl border bg-white p-5 shadow-sm sm:p-7">{context.ticket.status === "cerrado" ? <div className="flex gap-3 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600"><LockKeyhole className="size-5 shrink-0" /><p>Este ticket está cerrado. Si el problema continúa, crea un reporte nuevo.</p></div> : <><div className="mb-5 flex items-center gap-3"><LifeBuoy className="size-5 text-brand-green" /><h2 className="font-black text-brand-navy">Responder</h2></div><TicketReplyForm ticketId={ticketId} attachmentsEnabled={isR2Configured()} /></>}</section>
  </main>;
}
