create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete restrict,
  category text not null check (category in ('cuenta', 'menu', 'pedidos', 'cocina', 'equipo', 'qr', 'notificaciones', 'planes', 'seguridad', 'otro')),
  impact text not null check (impact in ('consulta', 'problema', 'bloqueado')),
  priority smallint generated always as (case impact when 'bloqueado' then 3 when 'problema' then 2 else 1 end) stored,
  status text not null default 'abierto' check (status in ('abierto', 'en_revision', 'esperando_cliente', 'resuelto', 'cerrado')),
  subject text not null check (char_length(trim(subject)) between 5 and 140),
  description text not null check (char_length(trim(description)) between 20 and 4000),
  page_url text check (page_url is null or char_length(page_url) <= 1000),
  user_agent text check (user_agent is null or char_length(user_agent) <= 500),
  app_version text check (app_version is null or char_length(app_version) <= 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz
);

create index support_tickets_restaurant_activity_idx on public.support_tickets (restaurant_id, last_activity_at desc);
create index support_tickets_creator_activity_idx on public.support_tickets (created_by, last_activity_at desc);
create index support_tickets_admin_queue_idx on public.support_tickets (status, priority desc, last_activity_at desc);

create table public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete restrict,
  body text not null check (char_length(trim(body)) between 2 and 4000),
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create index support_messages_ticket_created_idx on public.support_messages (ticket_id, created_at);

create table public.support_attachments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  message_id uuid references public.support_messages(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete restrict,
  object_key text not null unique,
  encryption_key text not null,
  encryption_iv text not null,
  original_name text not null check (char_length(original_name) between 1 and 180),
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  byte_size integer not null check (byte_size between 1 and 3145728),
  created_at timestamptz not null default now()
);

create index support_attachments_ticket_idx on public.support_attachments (ticket_id, created_at);
create index support_attachments_message_idx on public.support_attachments (message_id) where message_id is not null;

alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;
alter table public.support_attachments enable row level security;

-- Support data contains confidential operational details and encrypted-file keys.
-- It is deliberately accessible only through authenticated server routes using service_role.
revoke all on public.support_tickets, public.support_messages, public.support_attachments from anon, authenticated;
revoke all on sequence public.support_tickets_ticket_number_seq from anon, authenticated;

comment on table public.support_tickets is 'Tenant support cases managed through authorized CartaYa server routes.';
comment on table public.support_messages is 'Customer-visible and internal support conversation entries.';
comment on table public.support_attachments is 'Metadata and encryption material for encrypted R2 support attachments.';
